
---

- hosts: localhost

  vars:
    tobiko_run_tests: default

  tasks:

    - import_role:
        name: tobiko
      vars:
        tobiko_params:
          method: run_tests
          tests: "{{ tobiko_run_tests }}"
