
---

- hosts: localhost

  vars:

  tasks:

    - import_role:
        name: tobiko
      vars:
        tobiko_params:
          method: setup_test_resources
          hot_templates:
            - hot/templates/floating_ip.yaml
