
---

- name: combine config file with default config
  set_fact:
    tobiko_tempest_config: >
      {{ tobiko_tempest_default_config |
         combine(tobiko_config_from_file["tobiko-tempest"] | default({}),
                 recursive=True)
      }}
  when: item | succeeded
  with_items: "{{ tobiko_read_config_file.results }}"

- name: get tempest sources
  git:
    repo: "{{ tobiko_tempest_config.git_repo }}"
    dest: "{{ tobiko_tempest_config.src_dir }}/tempest"
    update: false
  register: tobiko_infrared_get_sources

- name: install tempest
  pip:
    name:
      - setuptools
      - pip
      - wheel
      - "{{ tobiko_tempest_config.src_dir }}/tempest"
    state: latest
    virtualenv: "{{ tobiko_tempest_config.venv_dir }}"
    chdir: "{{ tobiko_tempest_config.src_dir }}/tempest"
  when: tobiko_infrared_get_sources | changed

- name: get tempest plugins sources
  git:
    repo: "{{ item.git_repo }}"
    dest: "{{ tobiko_tempest_config.src_dir }}/{{ item.name }}"
    update: false
  register: tobiko_infrared_get_plugins_sources
  with_items: "{{ tobiko_tempest_config.plugins }}"

- name: install tempest plugins
  pip:
    name:
      - "{{ tobiko_tempest_config.src_dir }}/{{ item.item.name }}"
    state: latest
    virtualenv: "{{ tobiko_tempest_config.venv_dir }}"
    chdir: "{{ tobiko_tempest_config.src_dir }}/{{ item.item.name }}"
  when: item | changed
  with_items: "{{ tobiko_infrared_get_plugins_sources.results }}"
