
---

- name: openstack {{ tobiko_infrared_exec_params | mandatory }}
  shell: |
    source "{{ tobiko_infrared_config.venv_dir }}/bin/activate"
    source "{{ tobiko_infrared_config.setup_test_resources.stackrc_file }}"
    log_file="{{ tobiko_infrared_config.log_file }}"
    err_file="{{ tobiko_infrared_config.err_file }}"
    out_file="{{ tobiko_infrared_config.out_file }}"
    params=( {{ tobiko_infrared_exec_params }} -f yaml )
    (
      set -ex
      openstack "${params[@]}" > "${out_file}" 2> "${err_file}"
    ) >> "${log_file}" 2>&1
    result=$?
    cat "${out_file}" "${err_file}" >> "${log_file}"
    cat "${err_file}" 1>&2
    cat "${out_file}"
    exit ${result}

  register: tobiko_openstack_exec
  when: not tobiko_infrared_config.dry_run

- name: Get OpenStack output file
  slurp:
    src: "{{ tobiko_infrared_config.out_file }}"
  register: tobiko_openstack_read_output


- name: Parse OpenStack output file
  set_fact:
    tobiko_openstack_output: >
      {{ tobiko_openstack_read_output["content"] | b64decode | from_yaml }}


- name: Print OpenStack output
  debug:
    msg: "{{ tobiko_openstack_output }}"
