
---

tobiko_infrared_default_config:

  dry_run: false

  git_repo: "https://github.com/redhat-openstack/infrared.git"
  src_dir: "{{ tobiko_config.work_dir }}/infrared/src/infrared"
  venv_dir: "{{ tobiko_config.work_dir }}/infrared"
  log_file: "{{ tobiko_config.log_dir }}/infrared.log"
  out_file: "{{ tobiko_config.var_dir }}/infrared-stdout.txt"
  err_file: "{{ tobiko_config.var_dir }}/infrared-stderr.txt"

  mirror:

  setup_cloud:
    skip:

  setup_test_resources:
    skip:

  run_tests:
    skip:

  upgrade_cloud:
    skip:

  cleanup:
    skip:

  virsh:
    prov_file: "{{ tobiko_config.var_dir }}/virsh_prov.ini"
    generated_prov_file: "{{ tobiko_config.var_dir }}/generated_virsh_prov.ini"
    host_user: root
    host_address: localhost
    host_key: ~/.ssh/id_rsa
    host_memory_overcommit: false
    topology_nodes:
      - "undercloud:1"
      - "controller:1"
      - "compute:2"

  openstack:
    rc_file: "{{ tobiko_config.work_dir }}/infrared/overcloudrc"
    env_file: "{{ tobiko_config.work_dir }}/infrared/overcloud-env.yml"
    key_file: ~/.ssh/id_rsa
    cirros_image_url: "http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img"
    cirros_image_file: "{{ tobiko_config.work_dir }}/infrared/cirros-0.4.0-x86_64-disk.img"
    cirros_image_name: cirros-0.4.0
    small_flavor_name: small
    public_network_name: nova
    templates_dir: "{{ tobiko_config.var_dir }}/templates"

  tripleo_undercloud: {}

  tripleo_overcloud:
    network_dvr: no
    overcloud_templates: none

  tripleo_upgrade:
    fast: false

  tempest:
    default:
      blackre: []
      config_options: {}
      dir:
      image:
      image_packages: []
      mode: normal
      plugins: []
      packages:
        - gcc
        - python-devel
      pip_packages:
        - setuptools==40.0.0
      post_config_commands: []
      regexlist_file:
      remove_options: []
      results_formats: ['junitxml', 'html']
      revision:
      setup:
      tests: ['all']
      threads:
