
---

tobiko_infrared_default_config:

  dry_run: false

  git_repo: "https://github.com/redhat-openstack/infrared.git"
  src_dir: "{{ tobiko_config.work_dir }}/infrared/src/infrared"
  venv_dir: "{{ tobiko_config.work_dir }}/infrared"
  log_file: "{{ tobiko_config.log_dir }}/infrared.log"

  setup_cloud:
    skip:
    varsion:

  setup_test_resources:
    skip:

  run_tests:
    skip:

  upgrade_cloud:
    skip:
    version:
    fast: false

  cleanup:
    skip:

  virsh:
    host_address:
    host_key:
    host_memory_overcommit:
    topology_nodes:
      - "undercloud:1"
      - "controller:1"
      - "compute:2"

  tripleo_undercloud:
    mirror:

  tripleo_overcloud:
    network_dvr: no
    overcloud_templates: none

  tempest:
    default:
      blackre: []
      config_options: {}
      dir:
      image:
      image_packages: []
      mode: normal
      plugins: []
      packages:
        - gcc
        - python-devel
      pip_packages:
        - setuptools==40.0.0
      post_config_commands: []
      regexlist_file:
      remove_options: []
      results_formats: ['junitxml', 'html']
      revision:
      setup:
      tests: ['all']
      threads:
