
---

tobiko:

  setup_cloud:
    # skip: true
    # cleanup: false
    version: 12

  upgrade_cloud:
    version: 13

  setup_test_resources:
    # skip: true

  run_tests:
    skip: true
    tests:

      default:
        - neutron-tempest-plugin

      after_setup_test_resources:
        - neutron-tempest-plugin

      during_upgrade_cloud:
        - neutron-tempest-plugin

  cleanup:
    skip: false

  plugins:
    - tobiko-infrared


tobiko-infrared:

  dry_run: true

  virsh:
    # host_address: localhost
    # host_key: ~/.ssh/id_rsa
    host_memory_overcommit: false

  tripleo_undercloud:
    mirror: tlv

  tripleo_overcloud:
    network_dvr: yes

  tripleo_upgrade:
    # fast: true

  tempest:
    neutron-tempest-plugin:
      plugins:
        - "https://git.openstack.org/openstack/neutron-tempest-plugin"
