
---

- name: remove tobiko status file
  file:
    path: "{{ tobiko_config.work_dir }}/{{ tobiko_config.status_file }}"
    state: absent

- name: "delegate {{ tobiko_params.method }} to plugins: {{ tobiko_params }}"
  include_tasks: "{{ tobiko_plugin }}/tobiko-plugin.yml"
  with_items: "{{ tobiko_config.plugins | reverse | list }}"
  loop_control:
    loop_var: tobiko_plugin

- name: "clean complete"
  set_fact:
    tobiko_status: "{{ tobiko_default_status }}"
