
---

- name: cleanup cloud before setup
  include_tasks: cleanup.yml
  vars:
    tobiko_params:
      method: cleanup
  when: >
    tobiko_params.cleanup | default(tobiko_config.setup_cloud.cleanup) |
    default(true)

- name: "delegate {{ tobiko_params.method }} to plugins: {{ tobiko_params }}"
  include_tasks: "{{ tobiko_plugin }}.yml"
  with_items: "{{ tobiko_config.plugins }}"
  loop_control:
    loop_var: tobiko_plugin

- name: run tests after cloud setup
  include_role:
    name: tobiko
  vars:
    tobiko_params:
      method: run_tests
      tests: after_setup_cloud
