
---

- name: cleanup OpenStack hypervisor host
  include_tasks: infrared/exec.yml
  vars:
    infrared_args: >
      virsh
        --host-address "{{ tobiko_infrared_config.virsh.host_address }}"
        --host-key "{{ tobiko_infrared_config.virsh.host_key }}"
        --cleanup yes

