
---

- name: infrared {{ tobiko_infrared_exec_params | mandatory }}
  shell: |
    source "{{ tobiko_infrared_config.venv_dir }}/bin/activate"
    log_file="{{ tobiko_infrared_default_config.log_file }}"
    params=( {{ tobiko_infrared_exec_params }} )
    (
      set -ex
      infrared "${params[@]}"
    ) >> "${log_file}" 2>&1
  args:
    chdir: "{{ tobiko_infrared_config.src_dir }}"
  register: tobiko_infrared_exec
  when: not tobiko_infrared_config.dry_run
