
---

- name: install dos2unix
  yum:
    name: dos2unix
    state: present


- name: combine config file with default config
  set_fact:
    tobiko_infrared_config: >
      {{ tobiko_infrared_default_config |
         combine(tobiko_config_from_file["tobiko-infrared"] | default({}),
                 recursive=True)
      }}
  when: item is succeeded
  with_items: "{{ tobiko_read_config_file.results }}"


- name: get sources
  git:
    repo: "{{ tobiko_infrared_config.git_repo }}"
    dest: "{{ tobiko_infrared_config.src_dir }}"
    update: false
  register: tobiko_infrared_get_sources


- name: pupulate virtualenv
  pip:
    name:
      - setuptools
      - pip
      - wheel
      - python-openstackclient
      - python-heatclient
      - "{{ tobiko_infrared_config.src_dir }}"
    state: latest
    virtualenv: "{{ tobiko_infrared_config.venv_dir }}"
  when: tobiko_infrared_get_sources is changed


- name: install all InfraRed plugins
  include_tasks: ../exec/infrared.yml
  vars:
    tobiko_infrared_exec_params: >
      plugin add all


- name: simlink plugin roles into InfraRed tripleo-upgrade plugin
  file:
    src: "{{ tobiko_infrared_config.src_dir }}/plugins"
    dest: "{{ tobiko_infrared_config.src_dir }}/plugins/tripleo-upgrade/infrared_plugin/roles"
    state: link


- name: set mirror infrared option
  set_fact:
    tobiko_infrared_mirror: >
      {% if (tobiko_infrared_config.mirror | default(false)) %}
         --mirror {{ tobiko_infrared_config.mirror | quote }}
      {% endif %}


- name: get overcloudrc file
  include_tasks: exec/infrared.yml
  vars:
    tobiko_infrared_exec_params: >
      ssh undercloud-0 'cat overcloudrc'


- name: write overcloudrc file
  copy:
    src: "{{ tobiko_infrared_config.out_file }}"
    dest: "{{ tobiko_infrared_config.setup_test_resources.stackrc_file }}"
