
---

- name: combine config file with default config
  set_fact:
    tobiko_infrared_config: >
      {{ tobiko_infrared_default_config |
         combine(tobiko_config_from_file["tobiko-infrared"] | default({}),
                 recursive=True)
      }}
  when: item is succeeded
  with_items: "{{ tobiko_read_config_file.results }}"


- name: set derived config variables
  set_fact:
    virsh_config: "{{ tobiko_infrared_config.virsh }}"
    tripleo_undercloud_config: "{{ tobiko_infrared_config.tripleo_undercloud }}"
    tripleo_overcloud_config: "{{ tobiko_infrared_config.tripleo_overcloud }}"
    cloud_config: "{{ tobiko_infrared_config.cloud_config }}"
    tobiko_infrared_mirror: >
      {% if (tobiko_infrared_config.mirror | default(false)) %}
         --mirror {{ tobiko_infrared_config.mirror | quote }}
      {% endif %}


- name: get InfraRed sources
  git:
    repo: "{{ tobiko_infrared_config.git_repo }}"
    dest: "{{ tobiko_infrared_config.src_dir }}"
    update: "{{ tobiko_infrared_config.update_sources }}"
  register: tobiko_infrared_get_sources


- name: install InfraRed
  pip:
    name:
      - setuptools
      - pip
      - wheel
      - python-openstackclient
      - python-heatclient
      - "{{ tobiko_infrared_config.src_dir }}"
    state: latest
    virtualenv: "{{ tobiko_infrared_config.venv_dir }}"
  when: tobiko_infrared_get_sources is changed
  register: tobiko_infrared_install


- when: tobiko_infrared_install is changed
  block:

    - name: install InfraRed plugins
      include_tasks: ../infrared/exec.yml
      vars:
        infrared_args: >
          plugin add all

    - name: simlink plugin roles into InfraRed tripleo-upgrade plugin
      file:
        src: "{{ tobiko_infrared_config.src_dir }}/plugins"
        dest: "{{ tobiko_infrared_config.src_dir }}/plugins/tripleo-upgrade/infrared_plugin/roles"
        state: link
