
---

- name: init
  include_tasks: init.yml
  when: tobiko_infrared_config is not defined

- name: "{{ tobiko_params.method }}"
  include_tasks: "{{ tobiko_params.method }}.yml"
  when:
    - tobiko_params.method | default(false)
    - not (tobiko_infrared_config[tobiko_params.method].skip | default(false))
