
---

- name: put setup version to tobiko status
  set_fact:
    tobiko_status: >
      {{ tobiko_status |
         combine({
           'cloud': {
             'setup_version':
               (tobiko_params.version or
                tobiko_config.setup_cloud.version) | mandatory }},
           recursive=True) }}


- include_tasks: "setup/virsh.yml"
  vars:
    virsh_config: "{{ tobiko_infrared_config.virsh }}"


- include_tasks: "setup/tripleo_undercloud.yml"
  vars:
    tripleo_undercloud_config: >
      {{ tobiko_infrared_config.tripleo_undercloud }}


- include_tasks: "setup/tripleo_overcloud.yml"
  vars:
    tripleo_overcloud_config: >
      {{ tobiko_infrared_config.tripleo_overcloud }}


- name: setup {{ tobiko_params.version }} complete
  set_fact:
    tobiko_status: >
      {{ tobiko_status |
         combine({'cloud': {'version': tobiko_status.cloud.setup_version }},
                 recursive=True) }}
