
---

- name: put setup version to tobiko status
  set_fact:
    tobiko_status: >
      {{ tobiko_status |
         combine({
           'cloud': {
             'setup_version':
               (tobiko_params.version or
                tobiko_config.setup_cloud.version) | mandatory }},
           recursive=True) }}


- include_tasks: "setup/{{ item }}"
  with_items:
    - virsh.yml
    - tripleo_undercloud.yml
    - tripleo_overcloud.yml
    - cloud_config.yml


- name: setup {{ tobiko_params.version }} complete
  set_fact:
    tobiko_status: >
      {{ tobiko_status |
         combine({'cloud': {'version': tobiko_status.cloud.setup_version }},
                 recursive=True) }}
