
---

- name: introspect OpenStack overcloud nodes
  include_tasks: ../infrared/exec.yml
  vars:
    infrared_args: >
      tripleo-overcloud
        --version {{ tobiko_status.cloud.setup_version | quote }}
        --deployment-files virt
        --introspect yes
        --vbmc-force False
        --tagging no
        --deploy no

- name: tag OpenStack overcloud nodes
  include_tasks: ../infrared/exec.yml
  vars:
    infrared_args: >
      tripleo-overcloud
        --version {{ tobiko_status.cloud.setup_version | quote }}
        --deployment-files virt
        --introspect no
        --tagging yes
        --deploy no

- name: deploy OpenStack overcloud nodes
  include_tasks: ../infrared/exec.yml
  vars:
    infrared_args: >
      tripleo-overcloud
        --version {{ tobiko_status.cloud.setup_version | quote }}
        --deployment-files virt
        --introspect no
        --tagging no
        --deploy yes
        --overcloud-debug yes
        --overcloud-ssl no
        --overcloud-templates {{ tripleo_overcloud_config.overcloud_templates | quote}}
        --network-backend vlan
        --network-bgpvpn no
        --network-dvr {{ tripleo_overcloud_config.network_dvr | quote }}
        --network-l2gw no
        --network-protocol ipv4
        --storage-backend lvm
        --storage-external no
