
---

- name: deploy TripleO  undercoud
  include_tasks: ../infrared/exec.yml
  vars:
    infrared_args: >
      tripleo-undercloud
        --version {{ tobiko_status.cloud.setup_version | quote }}
        --images-task rpm
        --images-update yes
        {{ tobiko_infrared_mirror }}
