
---

- name: setup OpenStack undercoud host
  include_tasks: ../exec/infrared.yml
  vars:
    tobiko_infrared_exec_params: >
      tripleo-undercloud
        --version {{ tobiko_status.cloud.setup_version | quote }}

- name: populate OpenStack undercoud
  include_tasks: ../exec/infrared.yml
  vars:
    tobiko_infrared_exec_params: >
      tripleo-undercloud
        --images-task rpm
        --images-update yes

        {{ tobiko_infrared_mirror }}
